font = "JetBrainsMono Nerd Font"
border_size = 3 
animations = true

[colors]
background = "#575279"
inner_border_color = "#f2e9e1"

[colors.query_input]

selection = "#575279"
selection_background = "#dfdad9" 
text = "#575279"
background = "#faf4ed"

[colors.results_list]
selection = "#575279"
selection_background = "#dfdad9"
text = "#575279"
background = "#faf4ed"
scrollbar_color = "#575279"
scrollbar_hold_color = "#286983"


[colors.mode_label]
text = "#797593"
background = "#faf4ed"

[mode.apps]
dirs = [ 
  "/Applications/",
  "/System/Applications",
  "/Applications/Utilities/",
  "/System/Applications/Utilities",
]
show_icons = true
apps = ["/System/Library/CoreServices/Finder.app"]

[mode.files]
show_icons = true
dirs = ["$HOME/Library/Mobile Documents/com~apple~CloudDocs/"]
